spring:
  application:
    name: springboot-rocketmq
  jmx:
    default-domain: springboot-rocketmq
  profiles:
    active: dev #默认配置开发环境
server:
  port: 8088

---
spring:
  profiles: dev
  jackson: #时间格式转换
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    restart:
      enabled: true

# 第一种方式的配置
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: newGroup
    topic: newTopic
    secret-key: admin
    access-key: admin

# 第二种方式的配置    
apache:
  rocketmq:
    topic: consumerTopic
    consumerGroup: consumerProducer
    namesrvAddr: 127.0.0.1:9876