server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://139.224.228.48:13306/snippet?useSSL=false&autoReconnect=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: ZCH666mysql_
  cache:
    type: REDIS
    redis:
      cache-null-values: false
      time-to-live: 600000ms
      use-key-prefix: true
    cache-names: userCache,allUsersCache
  redis:
    host: 139.224.228.48
    port: 16379
    database: 0
    password: ZCH666redis_
    lettuce:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0