server.port: 8092

httpclient:
  connectTimeout: 20000
  requestTimeout: 20000
  socketTimeout: 30000
  defaultMaxPerRoute: 100
  maxTotalConnections: 300
  defaultKeepAliveTimeMillis: 20000
  closeIdleConnectionWaitTimeSecs: 30